**Hrithik Saha**

**ID: 0432310005101071**

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
A=np.array([[8+2, 8+1], [2*8, 8+2]])
print(A)

[[10  9]
 [16 10]]


In [3]:
# Finding shape
shape=np.shape(A)
print(shape)

# Finding Determinant
det_a=np.linalg.det(A)
print(det_a)

# Finding Rank
rank=np.linalg.matrix_rank(A)
print(rank)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

# Finding Inverse
if det_a!=0:
  inv_matrix=np.linalg.inv(A)
else:
  inv_matrix="Impossible"

print(inv_matrix)


(2, 2)
-43.99999999999999
2
[22. -2.]
[[ 0.6 -0.6]
 [ 0.8  0.8]]
[[-0.22727273  0.20454545]
 [ 0.36363636 -0.22727273]]


In [4]:
# New value is now at (1,2) position
B=np.array([[8+2, 8+1+1], [2*8, 8+2]])
print(B)


[[10 10]
 [16 10]]


In [5]:
# Finding shape
shape=np.shape(B)
print(shape)

# Finding Determinant
det_b=np.linalg.det(B)
print(det_b)

# Finding Rank
rank=np.linalg.matrix_rank(B)
print(rank)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)
print(eigenvalues)
print(eigenvectors)

# Finding Inverse
if det_b!=0:
  inv_matrix=np.linalg.inv(B)
else:
  inv_matrix="Impossible"

print(inv_matrix)

(2, 2)
-59.999999999999986
2
[22.64911064 -2.64911064]
[[ 0.62017367 -0.62017367]
 [ 0.78446454  0.78446454]]
[[-0.16666667  0.16666667]
 [ 0.26666667 -0.16666667]]
